---
name: Run pre-commit

on: pull_request

jobs:
  pre-commit-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: set PY
        run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Filter out changed files
        id: filter
        uses: dorny/paths-filter@v2
        with:
          list-files: shell
          filters: |
            changed:
              - '**'

      - name: Run pre-commit on changed files
        shell: bash
        if: steps.filter.outputs.changed == 'true'
        run: |
          pip install --quiet pre-commit
          pre-commit run --files ${{steps.filter.outputs.changed_files}} || echo "Exit status is $?"
